### ISSUE TITLE
ro.debuggable from build.prop

### ISSUE THREAD

**Issue by bigretromike** [Nanolx/magisk-nano-miitomo#4]
Probably not the place, but maybe you will know as you clam nano-miitomo just tick "ro.debuggable".
Could you maybe know why editing both default.prop and build.prop and setting "ro.debuggable=0" is not giving same results as this module?

**Comment by Nanolx** [comment]
ro.debuggable is usually found in default.prop, which is part of the ramdisk. That means you can't edit it without modifying the boot image. So while you may alter the copy of the file in use after boot up, the file gets reset on every reboot, thus re-setting ro.debuggable=1.

**Comment by bigretromike** [comment]
The file after reboot didnt looked like being reset but the thing you wrote make alot of sense. Could ypu shear info how to debug app and see what files it scan for root detection like you did with your other work?

**Comment by Nanolx** [comment]
I'm using 'logcats' to see what happens on the phone. I also use 'apktool' to decompile the apk and 'grep' for the usual keywords like 'root', 'su', 'emulator', 'SafetyNet' or whatever.

Maybe there are better ways, but for my purposes that's enough.
